import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Footer from "@/components/Footer";
import MouseFollower from "@/components/MouseFollower";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Riangle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="d-flex flex-column">
        <NavBar />

        <MouseFollower />
        {children}
        <Footer />
      </body>
    </html>
  );
}
